on:
  watch:
    types: [started]
jobs:
  poc_job:
    runs-on: ubuntu-latest
    name: Updater
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create a new text file with a randomized name
      run: |
        filename=$(echo $RANDOM | md5sum | cut -c 1-10).txt
        echo "Derogatory text" > $filename
        echo "Created file: $filename"

    - name: Upload the file as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: randomized-file
        path: "*.txt"
    - uses: EndBug/add-and-commit@v9
